# -*- coding: utf-8 -*-
"""Divide by 7 not multiple by 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtVaLrSnB6VTs9I8cWI3_s3atiHhggS9
"""

for i in range(2000, 3201):
  if((i%5 != 0) & (i%7 == 0)):
    print(i, end = ", ")