# -*- coding: utf-8 -*-
"""First_Name and Last_Name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cfe_N9sMbR2QHroO-7feh9JHJl4Bm0_m
"""

First_Name = str(input("Provide First Name "))
Last_Name = str(input("Provide Last Name "))
First_Name = First_Name[::-1]
Last_Name = Last_Name[::-1]
print(First_Name + " " + Last_Name)

