# -*- coding: utf-8 -*-
"""Volume of a sphere

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PAjSCCdvZxZ8ZIU8Tfe4LxBnjqVnl0ko
"""

import math

Diameter = 12
raidus = Diameter/2
Volume = (4/3) *  (math.pi) * (raidus)**3
print(Volume)